export const specialisation = [
  "Accounting",
  "Finance",
  "Admin",
  "Human Resources",
  "Building",
  "Construction",
  "Creative",
  "Customer Service",
  "Education / Training",
  "Engineering",
  "Financial Services & Banking",
  "Healthcare",
  "Information Technology",
  "Legal",
  "Manufacturing",
  "Marketing & Communications",
  "Others",
  "Project Management",
  "Product Management",
  "Sales",
  "Sciences",
  "Supply Chain & Logistics",
];

export const jobTypes = ["Freelance", "Internship", "Part Time", "Full Time"];

export const states = [
  "Kuala Lumpur",
  "Selangor",
  "Penang",
  "Johor",
  "Putrajaya",
  "Perlis",
  "Kedah",
  "Kelantan",
  "Terengganu",
  "Malacca",
  "Negeri Sembilan",
  "Pahang",
  "Perak",
  "Sabah",
  "Sarawak",
  "Labuan",
];
